Fix Unity 2019 compatibility in ConvertBlendshapeConventions: - PrefabulousHaiConvertBlendshapeConventions.cs(27,49): error CS1503: Argument 1: cannot convert from 'string' to 'char'